jobs:
- job: floskell_test_windows
  timeoutInMinutes: 120
  pool:
    vmImage: 'windows-2019'
  steps:
  - bash: |
      choco install -y --ignore-dependencies ghc --version=8.10.1 --force
      choco install -y cabal
      $(cygpath $ProgramData)/chocolatey/bin/RefreshEnv.cmd
      export GHCS_PATH=$(cygpath $ProgramData)/chocolatey/lib/ghc/tools
      export PATH=$GHCS_PATH/ghc-8.10.1/bin:$PATH
      cabal update
      cabal build -w ghc-8.10.1 || cabal build -w ghc-8.10.1
    displayName: 'cabal build'
