jobs:
- job: floskell_test_windows
  timeoutInMinutes: 120
  pool:
    vmImage: 'windows-2019'
  steps:
  - bash: |
      choco install -y --ignore-dependencies ghc --version=8.8.4 --force
      choco install -y --ignore-dependencies ghc --version=8.10.1 --force
      choco install -y --ignore-dependencies ghc --version=8.10.2 --force
      choco install -y cabal
      $(cygpath $ProgramData)/chocolatey/bin/RefreshEnv.cmd
      cabal build -w ghc-8.8.4 | cabal build -w ghc-8.10.1 | cabal build -w ghc-8.10.2
    displayName: 'cabal build'
