jobs:
- job: floskell_test_windows
  timeoutInMinutes: 120
  pool:
    vmImage: 'windows-2019'
  steps:
  - bash: |
      choco install -y --ignore-dependencies ghc --version=8.10.1 -m
      choco install -y cabal
      $(cygpath $ProgramData)/chocolatey/bin/RefreshEnv.cmd
      ls $(cygpath $ChocolateyInstall)/ghc.8.10.1/tools/ghc-8.10.1/bin
      ls $(cygpath $ChocolateyInstall)/ghc.8.8.4/tools/ghc-8.8.4/bin
      export PATH=$PATH:$(cygpath $ChocolateyInstall)/ghc.8.10.1/tools/ghc-8.10.1/bin
      export PATH=$PATH:$(cygpath $ChocolateyInstall)/ghc.8.8.4/tools/ghc-8.8.4/bin
      C:\ProgramData\chocolatey\lib\ghc.8.10.1\tools\ghc-8.10.1\bin
      cabal update
      cabal build -w ghc-8.8.4
      cabal build -w ghc-8.10.1
      cabal build -w ghc-8.10.2
    displayName: 'cabal build'
