jobs:
- job: ghcide_stack_windows
  timeoutInMinutes: 120
  pool:
    vmImage: 'windows-2019'
  steps:
  - bash: |
      choco install -y --ignore-dependencies ghc --version=8.8.4
      choco install -y cabal
      $(cygpath $ProgramData)/chocolatey/bin/RefreshEnv.cmd
      cabal build
    displayName: 'cabal build'
